export type Lang = 'en' | 'fa'

export interface Project {
  id: number
  title: string
  titleFa?: string
  description: string
  descriptionFa?: string
  tags: string[]
  color: string
  icon: string
  github: string | null
  live: string | null
  featured: boolean
}

export const projects: Project[] = [
  {
    id: 1,
    title: 'Bim Faa',
    titleFa: 'Bim Faa',
    description: 'BIM platform for multidisciplinary 3D building modeling — architecture, structural, mechanical, and electrical — enabling seamless coordination across design teams.',
    descriptionFa: 'پلتفرم مدلسازی اطلاعات ساختمان (BIM) در دیسیپلین‌های معماری، سازه، مکانیک و برق — هماهنگی یکپارچه میان تیم‌های طراحی.',
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'React.js'],
    color: '#0ea5e9',
    icon: 'Building2',
    github: null,
    live: 'https://bimfaa.ir',
    featured: true,
  },
  {
    id: 2,
    title: 'Apply Fa',
    titleFa: 'Apply Fa',
    description: 'Comprehensive portal for academic admissions, employment contracts, and Ausbildung placement in Germany — from document preparation to final acceptance.',
    descriptionFa: 'پورتال جامع اخذ پذیرش تحصیلی، قرارداد کاری و اوسبیلدونگ در آلمان — از آماده‌سازی مدارک تا پذیرش نهایی.',
    tags: ['Next.js', 'TypeScript', 'API Integration', 'Tailwind'],
    color: '#6366f1',
    icon: 'GraduationCap',
    github: null,
    live: 'https://applyfa.com',
    featured: true,
  },
  {
    id: 3,
    title: 'Watermark Builder',
    titleFa: 'واترمارک‌ساز',
    description: 'Browser-based batch watermarking tool — no server, no uploads. Drop images, configure text/logo watermarks, and export all at once. Built entirely with TypeScript and Canvas API.',
    descriptionFa: 'ابزار دسته‌جمعی واترمارک‌گذاری مستقیم در مرورگر — بدون سرور، بدون آپلود. تصویرها رو بنداز داخل، متن یا لوگو تنظیم کن و همه رو یه‌جا خروجی بگیر. کاملاً با TypeScript و Canvas API نوشته شده.',
    tags: ['TypeScript', 'Canvas API', 'Browser-only'],
    color: '#0891b2',
    icon: 'Droplets',
    github: 'https://github.com/Alirewa/watermark-builder',
    live: null,
    featured: true,
  },
  {
    id: 4,
    title: 'Inventory Manager',
    titleFa: 'مدیریت انبار',
    descriptionFa: 'اپلیکیشن کامل مدیریت موجودی با ردیابی کالا، هشدار موجودی و گزارش‌گیری. با JavaScript و Tailwind CSS ساخته شده و روی Vercel دیپلوی شده.',
    description: 'Full-featured inventory management application with product tracking, stock alerts, and reporting. Built with JavaScript and Tailwind CSS, deployed on Vercel.',
    tags: ['JavaScript', 'Tailwind CSS', 'LocalStorage'],
    color: '#10b981',
    icon: 'Package',
    github: 'https://github.com/Alirewa/Inventory-App',
    live: 'https://inventory-application-js.vercel.app',
    featured: true,
  },
  {
    id: 5,
    title: 'TG Bot → Google Drive',
    titleFa: 'ربات تلگرام → گوگل درایو',
    description: 'Python Telegram bot that automatically uploads any file sent to it directly to a configured Google Drive folder. Supports all file types with progress feedback.',
    descriptionFa: 'ربات تلگرامی با پایتون که هر فایلی بهش بفرستی رو مستقیم تو گوگل درایو آپلود می‌کنه. همه فرمت‌ها رو پشتیبانی می‌کنه با نمایش پیشرفت.',
    tags: ['Python', 'Telegram API', 'Google Drive API'],
    color: '#f59e0b',
    icon: 'FileUp',
    github: 'https://github.com/Alirewa/tg-bot-uploader-drive',
    live: null,
    featured: false,
  },
  {
    id: 6,
    title: 'Telegram Auto Sender',
    titleFa: 'ارسال‌گر خودکار تلگرام',
    description: 'Automated Telegram channel message sender built with TypeScript. Schedule and broadcast messages across multiple channels with configurable delays and templates.',
    descriptionFa: 'ابزار ارسال خودکار پیام به کانال‌های تلگرام با TypeScript. پیام رو زمان‌بندی کن و با تاخیر و قالب دلخواه به چند کانال پخش کن.',
    tags: ['TypeScript', 'Telegram API', 'Automation'],
    color: '#8b5cf6',
    icon: 'SendHorizontal',
    github: 'https://github.com/Alirewa/tg-bot-auto-sender',
    live: null,
    featured: false,
  },
  {
    id: 7,
    title: 'Note App',
    titleFa: 'اپ یادداشت',
    description: 'Clean, modular note-taking application with localStorage persistence. Demonstrates well-structured JavaScript architecture with create, edit, delete, and search functionality.',
    descriptionFa: 'اپ یادداشت‌برداری تمیز و ماژولار با ذخیره‌سازی لوکال. معماری ساختاریافته جاوااسکریپت با قابلیت ایجاد، ویرایش، حذف و جستجو.',
    tags: ['JavaScript', 'CSS', 'Modular JS'],
    color: '#ec4899',
    icon: 'StickyNote',
    github: 'https://github.com/Alirewa/NoteApp',
    live: 'https://note-app-alirewa.vercel.app',
    featured: false,
  },
  {
    id: 8,
    title: 'Shopping Cart',
    titleFa: 'سبد خرید',
    description: 'JavaScript shopping cart with add/remove items, quantity management, and localStorage-based state persistence. Clean UI with real-time total calculation.',
    descriptionFa: 'سبد خرید با جاوااسکریپت — افزودن/حذف کالا، مدیریت تعداد و ذخیره وضعیت در localStorage. رابط تمیز با محاسبه لحظه‌ای مجموع.',
    tags: ['JavaScript', 'CSS', 'LocalStorage'],
    color: '#14b8a6',
    icon: 'ShoppingCart',
    github: 'https://github.com/Alirewa/ShopingCart-App',
    live: null,
    featured: false,
  },
]

// ─── Per-language content ─────────────────────────────────────────────────────

export const content = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      skills: 'Skills',
      projects: 'Projects',
      contact: 'Contact',
    },
    hero: {
      greeting: "Hello, I'm",
      name: 'Alireza Pourgholam',
      roles: [
        'Frontend Developer',
        'React.js Expert',
        'Next.js Specialist',
        'UI/UX Enthusiast',
        'AI-Driven Developer',
      ],
      tagline: 'Frontend developer focused on building modern, fast, and user-centered interfaces. Passionate about web technologies, AI, and open-source.',
      cta: 'View My Work',
      ctaSecondary: 'Get In Touch',
      scrollHint: 'Scroll to explore',
      available: 'Available for freelance work',
    },
    about: {
      title: 'About Me',
      subtitle: 'Frontend developer · Open to freelance.',
      bio1: "Hi, I'm Alireza Pourgholam — a Frontend Developer passionate about building modern, practical user experiences. Based on Kish Island, I focus on fast, clean, and scalable UIs using the latest web technologies. From UI/UX design and implementation to performance optimization and frontend architecture, I always strive to balance visual aesthetics with great user experience.",
      bio2: "Throughout development I use AI tools like Claude, Cursor, Gemini, ChatGPT, and other smart assistants to make the process faster, more precise, and more efficient. I believe AI doesn't replace developers — it's a powerful tool for boosting productivity and staying focused on solving more meaningful problems.",
      bio3: "Beyond commercial work, I'm passionate about open-source. I spend part of my time building tools, libraries, and public projects, publishing them on GitHub so other developers can use, extend, or draw inspiration from them. Continuous learning, knowledge sharing, and contributing to the open-source community are some of my favorite parts of programming.",
      stats: [
        { value: '5+', label: 'Years Experience' },
        { value: '11+', label: 'Projects Delivered' },
        { value: '+50/wk', label: 'Weekly Contributions' },
      ],
      downloadCv: 'Download CV',
    },
    skills: {
      title: 'Technical Skills',
      subtitle: 'My technology stack — the tools I use to bring ideas to life.',
      categories: [
        {
          name: 'Frontend',
          badge: 'Primary Expertise',
          icon: 'Monitor',
          color: '#f59e0b',
          isPrimary: true,
          skills: [
            { name: 'React.js', level: 95 },
            { name: 'Next.js', level: 92 },
            { name: 'TypeScript', level: 88 },
            { name: 'Tailwind CSS', level: 95 },
            { name: 'Framer Motion', level: 80 },
            { name: 'Three.js / R3F', level: 70 },
          ],
        },
        {
          name: 'DevOps & Deploy',
          badge: 'Strong Skills',
          icon: 'Server',
          color: '#6b7280',
          isPrimary: false,
          skills: [
            { name: 'Git & GitHub', level: 92 },
            { name: 'Vercel', level: 88 },
            { name: 'Docker', level: 75 },
            { name: 'Linux', level: 70 },
            { name: 'CI/CD', level: 65 },
          ],
        },
        {
          name: 'Backend & APIs',
          badge: 'Supporting Role',
          icon: 'Wrench',
          color: '#6b7280',
          isPrimary: false,
          skills: [
            { name: 'Python', level: 82 },
            { name: 'Telegram Bot API', level: 88 },
            { name: 'REST APIs', level: 80 },
            { name: 'Node.js', level: 65 },
            { name: 'PostgreSQL', level: 60 },
          ],
        },
        {
          name: 'WordPress',
          badge: '3+ Years',
          icon: 'Globe',
          color: '#0073aa',
          isPrimary: false,
          skills: [
            { name: 'Custom Themes', level: 90 },
            { name: 'WooCommerce', level: 82 },
            { name: 'ACF / CPT', level: 85 },
            { name: 'PHP', level: 72 },
            { name: 'Performance & SEO', level: 78 },
          ],
        },
        {
          name: 'Graphic Design',
          badge: '2 Years',
          icon: 'Palette',
          color: '#f43f5e',
          isPrimary: false,
          skills: [
            { name: 'Brand Identity', level: 85 },
            { name: 'Ad Banners', level: 90 },
            { name: 'Icon Sets', level: 82 },
            { name: 'Mockup Design', level: 88 },
            { name: 'Visual Identity', level: 80 },
          ],
        },
      ],
    },
    projects: {
      title: 'Featured Projects',
      subtitle: "A curated selection of work I'm proud of.",
      viewMore: 'View All Projects',
      showLess: 'Show Less',
      liveDemo: 'Live',
      sourceCode: 'Code',
    },
    contact: {
      title: "Let's Work Together",
      subtitle: "Have a project in mind? I'd love to hear about it. Let's build something great together.",
      form: {
        name: 'Your Name',
        email: 'Your Email',
        message: 'Tell me about your project...',
        send: 'Send Message',
        sending: 'Sending...',
        success: "Message sent! I'll get back to you soon.",
        error: 'Something went wrong. Please try again.',
      },
      info: {
        phone: '+98 911 310 1767',
        email: 'alireza.pourgholam444@gmail.com',
        location: 'Kish Island, Iran',
        availability: 'Available for freelance',
      },
      social: [
        { name: 'GitHub', url: 'https://github.com/Alirewa', icon: 'Github' },
        { name: 'LinkedIn', url: 'https://linkedin.com/in/Alirewa', icon: 'Linkedin' },
        { name: 'Telegram', url: 'https://t.me/Alirewa', icon: 'Send' },
      ],
    },
    aiTools: {
      label: '// how I work',
      title: 'AI-Augmented Development',
      subtitle: 'I use tools like Claude, Cursor, Gemini, and ChatGPT throughout development to improve speed, code quality, and problem-solving — so I can focus more time on architecture, user experience, and meaningful decisions.',
      tools: [
        {
          name: 'Claude.ai',
          by: 'Anthropic',
          color: '#c084fc',
          badge: 'Primary',
          description: 'Architecture decisions, complex debugging, deep code review and system design. My primary reasoning partner.',
        },
        {
          name: 'Cursor',
          by: 'Anysphere',
          color: '#6366f1',
          badge: 'Daily editor',
          description: 'AI-native IDE with codebase-aware suggestions, inline diff generation, and context-rich chat.',
        },
        {
          name: 'ChatGPT',
          by: 'OpenAI',
          color: '#10b981',
          badge: 'Exploration',
          description: 'Rapid concept exploration, writing assistance, and quick prototyping of ideas before implementation.',
        },
        {
          name: 'Codex',
          by: 'OpenAI',
          color: '#f59e0b',
          badge: 'Automation',
          description: 'Automated code generation, boilerplate elimination, and scripting repetitive development tasks.',
        },
        {
          name: 'Antigravity',
          by: 'AI',
          color: '#38bdf8',
          badge: 'Workflow',
          description: 'Specialized AI assistant integrated into the development workflow for targeted productivity boosts.',
        },
      ],
    },
  },

  fa: {
    nav: {
      home: 'خانه',
      about: 'درباره من',
      skills: 'مهارت‌ها',
      projects: 'پروژه‌ها',
      contact: 'تماس',
    },
    hero: {
      greeting: 'سلام، من',
      name: 'علیرضا پورغلام',
      roles: [
        'توسعه‌دهنده فرانت‌اند',
        'متخصص React.js',
        'توسعه‌دهنده Next.js',
        'علاقه‌مند به UI/UX',
        'توسعه با هوش مصنوعی',
      ],
      tagline: 'فرانت‌اند کار می‌کنم — دوست دارم چیزایی بسازم که هم درست کار کنن هم خوب به نظر برسن. جذب تکنولوژی‌های وب، AI و پروژه‌های متن‌باز.',
      cta: 'نمونه‌کارها',
      ctaSecondary: 'تماس با من',
      scrollHint: 'بریم پایین',
      available: 'آماده همکاری فریلنسری',
    },
    about: {
      title: 'درباره من',
      subtitle: 'توسعه دهنده وب · آماده همکاری فریلنسری.',
      bio1: 'سلام، من علیرضا پورغلام هستم؛ توسعه‌دهنده فرانت‌اند و علاقه‌مند به ساخت تجربه‌های کاربری مدرن و کاربردی. در جزیره کیش فعالیت می‌کنم و تمرکزم روی توسعه رابط‌های کاربری سریع، تمیز و مقیاس‌پذیر با تکنولوژی‌های روز وب است. از طراحی و پیاده‌سازی UI/UX گرفته تا بهینه‌سازی عملکرد، معماری فرانت‌اند و تبدیل ایده‌ها به محصولی قابل استفاده، همیشه سعی می‌کنم بین زیبایی بصری و تجربه کاربری تعادل برقرار کنم.',
      bio2: 'در مسیر توسعه، از ابزارهای هوش مصنوعی مانند Claude، Cursor، Gemini، ChatGPT و سایر دستیارهای هوشمند به عنوان ابزارهای کمکی استفاده می‌کنم تا فرآیند توسعه سریع‌تر، دقیق‌تر و بهینه‌تر پیش برود. به نظرم هوش مصنوعی جایگزین توسعه‌دهنده نیست؛ بلکه ابزاری قدرتمند برای افزایش بهره‌وری و تمرکز روی حل مسائل مهم‌تر است.',
      bio3: 'علاوه بر پروژه‌های تجاری، به توسعه پروژه‌های متن‌باز نیز علاقه زیادی دارم. بخشی از زمانم را صرف ساخت ابزارها، کتابخانه‌ها و پروژه‌های عمومی می‌کنم و آن‌ها را در گیت‌هاب منتشر می‌کنم تا برای سایر توسعه‌دهندگان نیز مفید باشند. یادگیری مداوم، اشتراک دانش و مشارکت در جامعه متن‌باز از بخش‌های مورد علاقه من در دنیای برنامه‌نویسی است.',
      stats: [
        { value: '+۵', label: 'سال تجربه' },
        { value: '+۱۱', label: 'پروژه تحویل‌داده‌شده' },
        { value: '+۵۰', label: 'کانتریبیوت هفتگی' },
      ],
      downloadCv: 'دانلود رزومه',
    },
    skills: {
      title: 'مهارت‌های فنی',
      subtitle: 'استک من — ابزارایی که باهاشون ایده رو به کد تبدیل می‌کنم.',
      categories: [
        {
          name: 'فرانت‌اند',
          badge: 'تخصص اصلی',
          icon: 'Monitor',
          color: '#f59e0b',
          isPrimary: true,
          skills: [
            { name: 'React.js', level: 95 },
            { name: 'Next.js', level: 92 },
            { name: 'TypeScript', level: 88 },
            { name: 'Tailwind CSS', level: 95 },
            { name: 'Framer Motion', level: 80 },
            { name: 'Three.js / R3F', level: 70 },
          ],
        },
        {
          name: 'دپلوی و DevOps',
          badge: 'مهارت قوی',
          icon: 'Server',
          color: '#6b7280',
          isPrimary: false,
          skills: [
            { name: 'Git & GitHub', level: 92 },
            { name: 'Vercel', level: 88 },
            { name: 'Docker', level: 75 },
            { name: 'Linux', level: 80 },
            { name: 'CI/CD', level: 65 },
          ],
        },
        {
          name: 'بک‌اند و API',
          badge: 'نقش پشتیبان',
          icon: 'Wrench',
          color: '#6b7280',
          isPrimary: false,
          skills: [
            { name: 'Python', level: 82 },
            { name: 'Telegram Bot API', level: 88 },
            { name: 'REST APIs', level: 80 },
            { name: 'Node.js', level: 45 },
            { name: 'PostgreSQL', level: 55 },
          ],
        },
        {
          name: 'وردپرس',
          badge: '+۳ سال',
          icon: 'Globe',
          color: '#0073aa',
          isPrimary: false,
          skills: [
            { name: 'قالب اختصاصی', level: 90 },
            { name: 'WooCommerce', level: 82 },
            { name: 'ACF / CPT', level: 85 },
            { name: 'PHP', level: 72 },
            { name: 'سئو و بهینه‌سازی', level: 78 },
          ],
        },
        {
          name: 'طراحی گرافیک',
          badge: '۲ سال',
          icon: 'Palette',
          color: '#f43f5e',
          isPrimary: false,
          skills: [
            { name: 'هویت بصری برند', level: 85 },
            { name: 'بنر تبلیغاتی', level: 90 },
            { name: 'ست آیکن', level: 82 },
            { name: 'طراحی موکاپ', level: 88 },
            { name: 'هویت بصری', level: 80 },
          ],
        },
      ],
    },
    projects: {
      title: 'پروژه‌های انجام شده',
      subtitle: 'هر کدام برای رفع یک نیاز کوچک و یا بزرگ.',
      viewMore: 'مشاهده همه پروژه‌ها',
      showLess: 'نمایش کمتر',
      liveDemo: 'نمایش زنده',
      sourceCode: 'کد منبع',
    },
    contact: {
      title: 'باهم یه کاری بکنیم؟',
      subtitle: 'یه ایده داری؟ بگو بشنوم — دوست دارم روش کار کنیم.',
      form: {
        name: 'اسمت چیه؟',
        email: 'ایمیلت؟',
        message: 'پروژه‌ات رو برام توضیح بده...',
        send: 'بفرست',
        sending: 'داره می‌ره...',
        success: 'پیامت رسید! جواب می‌دم.',
        error: 'یه مشکلی پیش اومد — دوباره امتحان کن.',
      },
      info: {
        phone: '۰۹۱۱ ۳۱۰ ۱۷۶۷',
        email: 'alireza.pourgholam444@gmail.com',
        location: 'کیش، گلدیس، خ. وصال ۱، ساختمان اداری ایران، ط. دوم، واحد ۱۳',
        availability: 'آماده همکاری فریلنسری',
      },
      social: [
        { name: 'GitHub', url: 'https://github.com/Alirewa', icon: 'Github' },
        { name: 'LinkedIn', url: 'https://linkedin.com/in/Alirewa', icon: 'Linkedin' },
        { name: 'Telegram', url: 'https://t.me/Alirewa', icon: 'Send' },
      ],
    },
    aiTools: {
      label: '// رویکرد کاری من',
      title: 'توسعه با هوش مصنوعی',
      subtitle: 'تو کارم از Claude، Cursor، Gemini و ChatGPT استفاده می‌کنم — نه برای اینکه کد بنویسن، بلکه چون بهم کمک می‌کنن سریع‌تر فکر کنم و روی چیزای مهم‌تر وقت بذارم.',
      tools: [
        {
          name: 'Claude.ai',
          by: 'Anthropic',
          color: '#c084fc',
          badge: 'اصلی',
          description: 'برای تصمیم‌های معماری، دیباگ پیچیده و طراحی سیستم ازش کمک می‌گیرم. مثل یه همکار خوبه که همیشه در دسترسه.',
        },
        {
          name: 'Cursor',
          by: 'Anysphere',
          color: '#6366f1',
          badge: 'ادیتور روزانه',
          description: 'IDE ام که AI رو به کدبیس وصل می‌کنه — پیشنهاد درخطی، diff هوشمند و چت با context کامل.',
        },
        {
          name: 'ChatGPT',
          by: 'OpenAI',
          color: '#10b981',
          badge: 'ایده‌پردازی',
          description: 'وقتی می‌خوام یه ایده رو سریع بسنجم یا متن بنویسم، اول باهاش مشورت می‌کنم.',
        },
        {
          name: 'Codex',
          by: 'OpenAI',
          color: '#f59e0b',
          badge: 'اتوماسیون',
          description: 'کارای تکراری مثل boilerplate، اسکریپت‌ها و تبدیل کدها رو بهش می‌سپارم.',
        },
        {
          name: 'Antigravity',
          by: 'AI',
          color: '#38bdf8',
          badge: 'جریان کار',
          description: 'دستیار AI که مستقیم تو workflow توسعه‌ام جاسازی شده — برای افزایش تمرکز و سرعت.',
        },
      ],
    },
  },
}

export type Content = typeof content.en
